### ISSUE TITLE
Remote Disconnect

### ISSUE THREAD

**Issue by group-1-cns** [group-1-cns/CatastrophyPrj#51]
GitHub will not allow me to push/ fails everytime, saying that my branch (Genna) is disconnected from main. I have tried deleting my branch and making a new one, renaming my branch, checking to see if my Git LFS is properly set up and so on and so forth, but nothing has worked.

**Comment by AmoTachi** [comment]
Solution: Zip the original branch (just incase you need it if something messes up) and pull it out of the local github folder in your computer's files. Then reopen the GitHub desktop app and clone the original repository and wait for it to finish. It should be fine after that.
